language: nix
notifications:
    email: false

before_install:
    - make shell

script: make clean build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
